version: '3'

services:
  orders-db:
    container_name: orders-database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgres/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb
